#!/usr/bin/env python3
"""Admissible-class sweep for issue #641: does the nine-decile vector pin p_c?

Every full-rank sublattice of Z^2 has a unique Hermite normal form basis
{(h11, 0), (h21, h22)} with h11*h22 = N and 0 <= h21 < h11, so the distinct
finite periodic square-lattice quotients of site count N are exactly the HNF
triples (h11, h21, h22) with h11*h22 = N, modulo the D4 symmetry of the
square lattice (which preserves the NN and NNN step sets and hence the
geometry).  For each quotient the script computes the exact Mertens-Ziff
matching polynomial from the wrapping observable

    D(C) = 1{black NN wraps} - 1{white NN+NNN wraps}

by brute force over 2^N configurations (integer Bernstein coefficients),
builds the exact CDF F(p) = (1 + M(p))/2, isolates every physical root of M
and every decile quantile of F by exact Sturm bisection (Fraction only), and
ranks all geometry pairs by maximum decile-bracket gap against minimum
root-bracket gap.

The E4 rung is settled for the whole admissible class in the artifact text:
two different polynomials agreeing on an interval are identical, so equal
CDF-on-an-interval forces equal roots.

Run:  python scripts/decile_grid_pc_admissible_sweep.py --nmax 18
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from matched_torus_reference import Edge, Geometry, cluster_stats
from exact_polynomial_root_certificate import (
    fraction_text,
    isolate_roots,
    trim,
)

DECILES = tuple(Fraction(n, 10) for n in (1, 2, 3, 4, 5, 6, 7, 8, 9))
ISOLATION_BITS = 60


# ---------------------------------------------------------------- geometry


def hnf_fold(x: int, y: int, h11: int, h21: int, h22: int) -> tuple[int, int]:
    """Fold a covering point into the HNF fundamental rectangle."""
    k = (y - (y % h22)) // h22 if h22 else 0
    y2 = y % h22
    x2 = (x - k * h21) % h11
    return x2, y2


def d4_orbit_canonical(h11: int, h21: int, h22: int) -> tuple[int, int, int]:
    """Canonical D4-orbit representative of the sublattice, as HNF triple.

    D4 acts on Z^2 by the eight matrices (x,y) -> (±x, ±y) swapped or not.
    Each image sublattice is re-reduced to HNF and the lexicographically
    smallest triple is kept.
    """
    best: tuple[int, int, int] | None = None
    for swap in (False, True):
        for sx in (1, -1):
            for sy in (1, -1):
                def apply(vec: tuple[int, int]) -> tuple[int, int]:
                    x, y = vec
                    if swap:
                        x, y = y, x
                    return (sx * x, sy * y)

                v1 = apply((h11, 0))
                v2 = apply((h21, h22))
                triple = hnf_of_basis(v1, v2)
                if best is None or triple < best:
                    best = triple
    assert best is not None
    return best


def hnf_of_basis(v1: tuple[int, int], v2: tuple[int, int]) -> tuple[int, int, int]:
    """Unique HNF triple of the sublattice generated by v1, v2."""
    # column-style HNF over rows: find (h11, 0) = a*v1 + b*v2 with minimal h11>0
    a1, b1 = v1
    a2, b2 = v2
    det = a1 * b2 - a2 * b1
    if det < 0:
        v1, v2 = v2, v1
        a1, b1, a2, b2 = a2, b2, a1, b1
        det = -det
    # lattice = {m v1 + k v2}; y-component condition: b1*m + b2*k = 0
    if b1 == 0 and b2 == 0:
        # both vectors horizontal: lattice is 1-dimensional, not full rank
        raise ValueError("degenerate basis")
    # (h11, 0): solve b1*m + b2*k = 0 -> (m,k) = t*(b2/g, -b1/g), g = gcd(b1,b2)
    g = math.gcd(b1, b2)
    if g == 0:
        # b1 == b2 == 0 impossible (full rank)
        raise ValueError("degenerate basis")
    m0, k0 = b2 // g, -b1 // g
    h11 = abs(m0 * a1 + k0 * a2)
    if h11 == 0:
        raise ValueError("degenerate basis")
    # h22: index / h11, index = det
    h22 = det // h11
    if h11 * h22 != det:
        raise AssertionError("HNF factorisation failed")
    # h21: x-component of a lattice vector with y = h22:
    #   y = b1*m + b2*k = h22; particular solution plus kernel t*(m0,k0)
    # minimize x = a1*m + a2*k over solutions, then reduce mod h11
    if b1 == 0:
        # v1 horizontal: (h11,0)=v1; (x,h22) must be in span; from v2 direction
        # lattice y-values are multiples of g=gcd(0,b2)=|b2|; h22=det/h11
        # solve b2*k = h22
        if h22 % b2 != 0:
            raise AssertionError("b1=0 HNF inconsistency")
        k = h22 // b2
        h21 = (a2 * k) % h11
    elif b2 == 0:
        if h22 % b1 != 0:
            raise AssertionError("b2=0 HNF inconsistency")
        m = h22 // b1
        h21 = (a1 * m) % h11
    else:
        # solve b1*m + b2*k = h22
        # particular via extended gcd
        g1 = math.gcd(b1, b2)
        if h22 % g1 != 0:
            raise AssertionError("HNF y-solve inconsistency")
        # b1*(m0') + b2*(k0') = g1
        def ext_gcd(a: int, b: int) -> tuple[int, int, int]:
            if b == 0:
                return a, 1, 0
            g, x, y = ext_gcd(b, a % b)
            return g, y, x - (a // b) * y
        _g, u, w = ext_gcd(b1, b2)
        scale = h22 // g1
        m_p, k_p = u * scale, w * scale
        # kernel: (m,k) = (m_p,k_p) + t*(m0,k0)
        best_x = None
        # search small t window (x is linear in t, so the min mod h11 needs care;
        # we only need x mod h11, and any solution works)
        x0 = a1 * m_p + a2 * k_p
        dx = a1 * m0 + a2 * k0
        # x(t) = x0 + t*dx; want x mod h11 canonical: reduce x0 by moving t so
        # that x0 + t*dx lands in [0, h11) when dx invertible mod h11, else scan
        if dx % h11 == 0:
            h21 = x0 % h11
        else:
            # find t with x0 + t*dx ≡ r (mod h11) for the true minimal set;
            # since we only need one representative mod h11 of the achievable
            # residues, solve dx*t ≡ (target - x0): all residues in the coset
            # dx*Z + x0 mod h11; pick the minimal residue in that coset.
            gd = math.gcd(dx % h11, h11)
            base = x0 % h11
            reachable = {r for r in range(gd) if (base + r) % gd == base % gd}
            # residues are base + multiples of gd mod h11
            candidates = [(base + t * gd) % h11 for t in range(h11 // gd + 1)]
            h21 = min(candidates)
    return (h11, h21, h22)


def enumerate_sublattices(n_max: int) -> list[tuple[int, int, int]]:
    """D4-canonical HNF triples with index <= n_max."""
    seen = set()
    out = []
    for det in range(1, n_max + 1):
        for h22 in range(1, det + 1):
            if det % h22:
                continue
            h11 = det // h22
            for h21 in range(h11):
                triple = d4_orbit_canonical(h11, h21, h22)
                if triple[0] * triple[2] != det:
                    continue
                if triple not in seen:
                    seen.add(triple)
                    out.append(triple)
    return out


def build_geometry_hnf(triple: tuple[int, int, int]) -> Geometry:
    h11, h21, h22 = triple
    det = h11 * h22
    coordinates = tuple(
        (x, y) for y in range(h22) for x in range(h11)
    )
    ids = {coord: i for i, coord in enumerate(coordinates)}

    def make_edges(steps: tuple[tuple[int, int], ...]) -> tuple[Edge, ...]:
        edges = []
        for i, (x, y) in enumerate(coordinates):
            for dx, dy in steps:
                j = ids[hnf_fold(x + dx, y + dy, h11, h21, h22)]
                edges.append(Edge(i=i, j=j, dx=dx, dy=dy))
        return tuple(edges)

    nn = ((1, 0), (0, 1))
    nnn = ((1, 1), (1, -1))
    return Geometry(
        name=f"HNF({h11},{h21},{h22})",
        L=det,
        coordinates=coordinates,
        primal_edges=make_edges(nn),
        matching_edges=make_edges(nn + nnn),
        physical_period=f"basis (h11={h11},0), (h21={h21},h22={h22})",
    )


# ---------------------------------------------------------------- exact M


def bernstein_counts(geometry: Geometry) -> list[int]:
    counts = [0] * (geometry.n + 1)
    n_sites = geometry.n
    for mask in range(1 << n_sites):
        k = bin(mask).count("1")
        black = [bool((mask >> i) & 1) for i in range(n_sites)]
        _nb, black_wrap = cluster_stats(black, geometry.primal_edges)
        white = [not value for value in black]
        _nw, white_wrap = cluster_stats(white, geometry.matching_edges)
        counts[k] += int(black_wrap) - int(white_wrap)
    return counts


def bernstein_to_power(counts: list[int]) -> list[int]:
    from math import comb
    n = len(counts) - 1
    coefficients = [0] * (n + 1)
    for k, value in enumerate(counts):
        if value:
            for degree in range(k, n + 1):
                coefficients[degree] += (
                    value * (-1) ** (degree - k) * comb(n - k, degree - k)
                )
    return trim(coefficients)


def cdf_from_counts(counts: list[int]) -> list[Fraction]:
    m_power = bernstein_to_power(counts)
    half = [Fraction(v, 2) for v in m_power]
    if not half:
        half = [Fraction(0)]
    half[0] += Fraction(1, 2)
    return trim(half)


def evaluate_m(counts: list[int], p: Fraction) -> Fraction:
    n = len(counts) - 1
    total = Fraction(0)
    for k, value in enumerate(counts):
        if value:
            total += value * p**k * (1 - p) ** (n - k)
    return total


def bracket_gap(a, b):
    if a[1] < b[0]:
        return b[0] - a[1]
    if b[1] < a[0]:
        return a[0] - b[1]
    return Fraction(0)


def sweep_record(geometry: Geometry) -> dict:
    counts = bernstein_counts(geometry)
    m_power = bernstein_to_power(counts)
    cdf = cdf_from_counts(counts)
    m_roots = isolate_roots(m_power, bits=ISOLATION_BITS)
    deciles = {}
    for u in DECILES:
        polynomial = list(cdf)
        polynomial[0] -= u
        brackets = isolate_roots(polynomial, bits=ISOLATION_BITS)
        if len(brackets) != 1:
            raise AssertionError(
                f"{geometry.name}: decile u={u} has {len(brackets)} brackets"
            )
        deciles[u] = brackets[0]
    return {
        "name": geometry.name,
        "n": geometry.n,
        "period": geometry.physical_period,
        "bernstein_counts": counts,
        "m_power": [int(v) for v in m_power],
        "m_roots": [f"({fraction_text(l)}, {fraction_text(r)})" for l, r in m_roots],
        "deciles": {
            fraction_text(u): f"({fraction_text(l)}, {fraction_text(r)})"
            for u, (l, r) in deciles.items()
        },
        "m_half": fraction_text(evaluate_m(counts, Fraction(1, 2))),
        "_deciles": deciles,
        "_m_roots": m_roots,
        "_m_half": evaluate_m(counts, Fraction(1, 2)),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--nmax", type=int, default=18)
    parser.add_argument("--top", type=int, default=25)
    args = parser.parse_args()

    triples = enumerate_sublattices(args.nmax)
    print(f"{len(triples)} distinct D4-orbit sublattices with N <= {args.nmax}")

    records: list[dict] = []
    seen_m: dict[tuple, str] = {}
    for triple in triples:
        geometry = build_geometry_hnf(triple)
        try:
            record = sweep_record(geometry)
        except AssertionError as exc:
            print(f"  FAIL {geometry.name}: {exc}")
            continue
        key = tuple(record["m_power"])
        if key in seen_m:
            print(f"  {geometry.name}: M identical to {seen_m[key]}, deduped")
            continue
        seen_m[key] = geometry.name
        records.append(record)
        print(
            f"  {geometry.name}: N={record['n']} M(1/2)={record['m_half']} "
            f"roots={len(record['_m_roots'])}"
        )

    pairs = []
    for i in range(len(records)):
        for j in range(i + 1, len(records)):
            a, b = records[i], records[j]
            max_gap = max(
                bracket_gap(a["_deciles"][u], b["_deciles"][u]) for u in DECILES
            )
            root_gap = min(
                bracket_gap(ra, rb)
                for ra in a["_m_roots"]
                for rb in b["_m_roots"]
            )
            pairs.append({
                "pair": f"{a['name']} vs {b['name']}",
                "max_decile_bracket_gap": fraction_text(max_gap),
                "max_decile_bracket_gap_float": float(max_gap),
                "min_root_bracket_gap": fraction_text(root_gap),
                "min_root_bracket_gap_float": float(root_gap),
                "m_half_equal": str(a["_m_half"]) == str(b["_m_half"]),
            })
    pairs.sort(key=lambda p: p["max_decile_bracket_gap_float"])

    artifact = {
        "schema": "matching-one/decile-grid-pc-admissible-sweep/v1",
        "issue": 641,
        "data_class": "exact Fraction arithmetic; Sturm isolation bits=60",
        "n_max": args.nmax,
        "geometries_tested": len(records),
        "e4_argument": (
            "E4 fails for every admissible pair with M1 != M2: if two CDF "
            "polynomials agree on an interval [p1,p2] with nonempty interior, "
            "they are the same polynomial, hence M1 = M2 and the physical "
            "roots coincide. E4 succeeding would need one geometry's M to "
            "have a different root than itself. Settled by polynomial "
            "identity, not by the sweep."
        ),
        "best_pairs": pairs[: args.top],
    }
    out_dir = ROOT / "results" / "decile-grid-pc"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "admissible-sweep.json"
    out_path.write_text(json.dumps(artifact, indent=2), encoding="utf-8")
    print(f"\nwrote {out_path}")
    print("\nClosest pairs by max decile bracket gap:")
    for pair in pairs[: args.top]:
        print(
            f"  {pair['pair']}: decile ~ {pair['max_decile_bracket_gap_float']:.3e}, "
            f"root ~ {pair['min_root_bracket_gap_float']:.3e}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
