#!/usr/bin/env python3
"""#598 Phase A/B: the symmetry-breaking direction is first-order invisible.

#580 reported that a localized out-of-pencil tilt (``single_point_join``)
destroys P398's exact positive lumping at every width -- the coarsest admissible
partition collapses to the identity -- while #580/#588 found the frozen
finite-horizon input/output description barely moves.  That contrast was written
up as "the positive state is fragile".  #598 proposes a much better explanation,
and this script tests it exactly.

The proposal has two halves.

**Half one: the positive block count is an orbit count.**  The reported
``r_positive = 10, 26, 76, 232, 750`` for widths 4-8 equals

    r_reflect(w) = [ Catalan(w) + binom(w, floor(w/2)) ] / 2,

which is Burnside's count for the group generated by a single reflection.  This
script verifies that arithmetic *and* the fact that makes it much weaker than it
looks: **every** reflection of the cycle fixes exactly ``binom(w, floor(w/2))``
noncrossing states, so the count alone does not identify which reflection.  The
identification has to come from the task, and it does: exactly one reflection
preserves the declared dictionary at every width.

**Half two: a parity selection rule.**  With ``R`` that reflection, write

    H_single = H_even + H_odd,
    H_even = (H_single + R H_single R)/2,
    H_odd  = (H_single - R H_single R)/2.

If the baseline generator is ``R``-equivariant and the declared source ``mu`` and
readout ``f`` are ``R``-even, then the first-order response to ``H_odd`` vanishes
*pointwise in the time integrand*, not merely on average:

    mu^T e^{(t-s)G} H_odd e^{sG} f = 0   for every 0 <= s <= t,

because ``e^{sG}f`` stays even, ``H_odd`` maps even to odd, and an even measure
annihilates an odd function.  So an exact quotient can be destroyed by an
arbitrarily small intervention while every invariant finite-horizon task stays
blind to the breaking direction at ``O(eps)``.

This is checked as a chain of exact sector statements rather than by
differentiating an exponential, which makes it a theorem test instead of a
numerical coincidence.  Phase B then confirms the consequence empirically: for
even tasks the gap between the full tilt and its even part must be ``O(eps^2)``.

The test can fail, and one built-in case shows how: ``halves_linked`` is *not*
``R``-even at odd widths, so at ``w = 5`` and ``w = 7`` its first-order response
to ``H_odd`` is required to be nonzero.  A run in which everything vanishes is a
broken test, not a stronger theorem.
"""

from __future__ import annotations

import argparse
import json
import math
from fractions import Fraction
from pathlib import Path
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple

if __package__ in (None, ""):
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))

from noncrossing_connectivity_codec import canonical_rgs, noncrossing_states  # noqa: E402
from p398_intervention_transport import (  # noqa: E402
    HELD_OUT_READOUTS,
    PRIMARY_READOUTS,
    Generator,
    matvec,
    source_distributions,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "results" / "p398-reflection-parity" / "latest.json"
SCHEMA = "matching-one.p398-reflection-parity.v1"
ISSUE = 598

DEFAULT_WIDTHS: Tuple[int, ...] = (4, 5, 6, 7, 8)

#: #580's reported coarsest exact admissible positive lumping block counts.
#: Quoted here so the orbit formula is checked against the published numbers
#: rather than against a fresh recomputation that could drift with it.
REPORTED_R_POSITIVE = {4: 10, 5: 26, 6: 76, 7: 232, 8: 750}

#: The declared dictionary, in the order #580 froze it.  ``D0`` is the span
#: seed; the five held-out readouts are never used to build anything.
READOUTS: Tuple[Tuple[str, Callable[[Sequence[int]], float]], ...] = (
    PRIMARY_READOUTS + HELD_OUT_READOUTS
)
D0_NAMES: Tuple[str, ...] = tuple(name for name, _ in PRIMARY_READOUTS)

#: Declared (s, t) grid for the pointwise selection-rule check.  ``s`` is given
#: as a fraction of ``t`` so that every pair satisfies 0 < s < t by construction.
LAGS: Tuple[float, ...] = (0.5, 1.0, 2.0)
SPLIT_FRACTIONS: Tuple[float, ...] = (0.25, 0.5, 0.75)

#: Declared epsilon ladder for Phase B.  Symmetric, so an odd-order contamination
#: would show up as an asymmetry rather than hide in the fit.
EPSILONS: Tuple[float, ...] = (0.0625, 0.125, 0.25)

#: Uniformization truncation: terms are added until the remaining Poisson mass is
#: below this, capped by MAX_POISSON.  A vector-valued Krylov cache ``P^k v`` is
#: built once per vector and reused for every time, which is what makes the whole
#: (s, t) grid affordable at width 8.
POISSON_TAIL = 1e-15
MAX_POISSON = 400

#: A relative residual above this is reported as a failure of the sector claim.
#: Set at 1e-10 rather than at machine epsilon because the uniformization sum
#: accumulates ~10^2 terms of alternating magnitude; anything genuinely nonzero
#: in these tests is O(1), not O(1e-9).
SECTOR_TOLERANCE = 1e-10


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


# --------------------------------------------------------------------------
# The dihedral action on noncrossing states
# --------------------------------------------------------------------------


def apply_permutation(state: Sequence[int], permutation: Sequence[int]) -> Tuple[int, ...]:
    """Relabel a connectivity state by moving point ``i`` to ``permutation[i]``."""

    width = len(state)
    inverse = [0] * width
    for source, destination in enumerate(permutation):
        inverse[destination] = source
    return canonical_rgs([state[inverse[j]] for j in range(width)])


def rotation(width: int, k: int) -> List[int]:
    return [(i + k) % width for i in range(width)]


def reflection(width: int, k: int) -> List[int]:
    """The reflection ``i -> k - i`` of the cycle."""

    return [(k - i) % width for i in range(width)]


def state_permutation(generator: Generator, permutation: Sequence[int]) -> List[int]:
    """The induced permutation of state indices."""

    rank = {state: index for index, state in enumerate(generator.states)}
    return [rank[apply_permutation(state, permutation)] for state in generator.states]


def is_involution(pi: Sequence[int]) -> bool:
    return all(pi[pi[i]] == i for i in range(len(pi)))


def invariant_observable(
    generator: Generator, pi: Sequence[int], values: Sequence[float]
) -> bool:
    return all(values[pi[i]] == values[i] for i in range(generator.size))


# --------------------------------------------------------------------------
# Half one: is the positive block count an orbit count, and of which reflection?
# --------------------------------------------------------------------------


def catalan(width: int) -> int:
    return math.comb(2 * width, width) // (width + 1)


def orbit_count(pi: Sequence[int]) -> int:
    """Number of orbits of an involution, by Burnside: ``(|X| + |Fix|)/2``."""

    _require(is_involution(pi), "orbit_count expects an involution")
    fixed = sum(1 for i in range(len(pi)) if pi[i] == i)
    return (len(pi) + fixed) // 2


def reflection_survey(generator: Generator) -> Dict[str, Any]:
    """Fixed-point and orbit counts for every reflection, plus the task filter.

    Two separate facts come out of this, and conflating them would overstate the
    result.  First, *every* reflection has the same fixed-point count, so the
    Burnside match to ``r_positive`` is a necessary condition that identifies
    nothing.  Second, the declared dictionary is preserved by exactly one of
    them, and *that* is what names ``R``.
    """

    width = generator.width
    values = {
        name: [function(state) for state in generator.states]
        for name, function in READOUTS
    }
    sources = {name: vector for name, vector in source_distributions(generator)}

    rows = []
    d0_preserving = []
    all_preserving = []
    for k in range(width):
        pi = state_permutation(generator, reflection(width, k))
        _require(is_involution(pi), f"reflection {k} is not an involution on states")
        preserved = [name for name, _ in READOUTS if invariant_observable(generator, pi, values[name])]
        source_preserved = [
            name for name, vector in sources.items()
            if invariant_observable(generator, pi, vector)
        ]
        rows.append({
            "reflection": f"i -> {k} - i",
            "k": k,
            "fixed_states": sum(1 for i in range(generator.size) if pi[i] == i),
            "orbits": orbit_count(pi),
            "readouts_preserved": preserved,
            "sources_preserved": source_preserved,
        })
        if set(D0_NAMES) <= set(preserved):
            d0_preserving.append(k)
        if len(preserved) == len(READOUTS):
            all_preserving.append(k)

    central = math.comb(width, width // 2)
    return {
        "by_reflection": rows,
        "all_reflections_have_the_same_fixed_count": len({row["fixed_states"] for row in rows}) == 1,
        "central_binomial": central,
        "fixed_count_equals_central_binomial": all(
            row["fixed_states"] == central for row in rows
        ),
        "reflections_preserving_D0": d0_preserving,
        "reflections_preserving_all_readouts": all_preserving,
        "task_compatible_k": d0_preserving[0] if len(d0_preserving) == 1 else None,
    }


def burnside_check(generator: Generator, k: int) -> Dict[str, Any]:
    pi = state_permutation(generator, reflection(generator.width, k))
    width = generator.width
    formula = (catalan(width) + math.comb(width, width // 2)) // 2
    counted = orbit_count(pi)
    reported = REPORTED_R_POSITIVE.get(width)
    return {
        "catalan": catalan(width),
        "central_binomial": math.comb(width, width // 2),
        "r_reflect_formula": formula,
        "orbits_counted": counted,
        "formula_matches_count": formula == counted,
        "reported_r_positive": reported,
        "matches_reported_r_positive": reported is not None and reported == counted,
        "caveat": (
            "Every reflection gives this same orbit count, so agreement with "
            "r_positive is necessary and not identifying.  What names R is the "
            "declared dictionary, not this number.  Agreement here also does not "
            "show that the coarsest admissible lumping *is* the orbit partition "
            "-- only that the two have the same cardinality."
        ),
    }


# --------------------------------------------------------------------------
# The decisive Gate-1 comparison: is the coarsest lumping the orbit partition?
# --------------------------------------------------------------------------


def observable_partition(
    generator: Generator, names: Sequence[str]
) -> List[int]:
    """Initial partition: states agreeing on every named readout.

    Admissibility is not optional.  A lumping that merged two states the
    dictionary distinguishes could not carry the declared readouts, so the
    refinement has to start here rather than from the one-block partition.
    """

    lookup = dict(READOUTS)
    signature: Dict[Tuple[float, ...], int] = {}
    labels = []
    for state in generator.states:
        key = tuple(lookup[name](state) for name in names)
        if key not in signature:
            signature[key] = len(signature)
        labels.append(signature[key])
    return labels


def coarsest_lumping(
    generator: Generator,
    rate_sets: Sequence[Mapping[Tuple[str, int], float]],
    labels: Sequence[int],
) -> List[int]:
    """Coarsest strong lumping refining ``labels`` and stable for every rate set.

    Strong lumpability asks that for states ``i, j`` in one block and any block
    ``C``, the total rate into ``C`` agrees.  Requiring it for ``J`` and ``D``
    separately is the same as requiring it for the whole affine pencil, since
    ``G_eta`` is a linear combination of the two with the coefficients varying:
    a partition stable for two independent members of a two-dimensional pencil
    is stable for all of it.
    """

    labels = list(labels)
    operators = [generator.rows(rates) for rates in rate_sets]
    while True:
        signature: Dict[Tuple[Any, ...], int] = {}
        refined = []
        for source in range(generator.size):
            key: List[Any] = [labels[source]]
            for rows in operators:
                totals: Dict[int, float] = {}
                for destination, value in rows[source]:
                    block = labels[destination]
                    totals[block] = totals.get(block, 0.0) + value
                key.append(tuple(sorted(totals.items())))
            frozen = tuple(key)
            if frozen not in signature:
                signature[frozen] = len(signature)
            refined.append(signature[frozen])
        if refined == labels:
            return labels
        labels = refined


def canonical_labels(labels: Sequence[int]) -> Tuple[int, ...]:
    return canonical_rgs(list(labels))


def orbit_labels(generator: Generator, k: int) -> List[int]:
    pi = state_permutation(generator, reflection(generator.width, k))
    labels = [-1] * generator.size
    next_label = 0
    for i in range(generator.size):
        if labels[i] < 0:
            labels[i] = labels[pi[i]] = next_label
            next_label += 1
    return labels


def lumping_comparison(generator: Generator, k: int) -> Dict[str, Any]:
    """Compare the coarsest admissible lumping with the reflection-orbit partition.

    This is the question #596's Gate 1 actually asks, and cardinality does not
    answer it: two partitions with 750 blocks each need not be the same
    partition.  Because every admissible lumping refines the coarsest one, an
    orbit partition that is itself admissible and has the same block count must
    *be* the coarsest -- so equality here is decidable, not approximate.
    """

    baseline = {move: 1.0 for move in generator.moves}
    joins = {move: (1.0 if move[0] == "join" else 0.0) for move in generator.moves}
    detaches = {move: (1.0 if move[0] == "detach" else 0.0) for move in generator.moves}

    out: Dict[str, Any] = {}
    for label, names in (("D0", D0_NAMES), ("all_readouts", tuple(name for name, _ in READOUTS))):
        initial = observable_partition(generator, names)
        coarsest = coarsest_lumping(generator, (joins, detaches), initial)
        orbits = orbit_labels(generator, k)
        orbit_is_admissible = canonical_labels(
            coarsest_lumping(generator, (joins, detaches), orbits)
        ) == canonical_labels(orbits)
        out[label] = {
            "initial_blocks": len(set(initial)),
            "coarsest_blocks": len(set(coarsest)),
            "orbit_blocks": len(set(orbits)),
            "orbit_partition_is_admissible": orbit_is_admissible,
            "coarsest_equals_orbit_partition": canonical_labels(coarsest) == canonical_labels(orbits),
        }
    out["baseline_is_pencil_sum"] = all(
        baseline[move] == joins[move] + detaches[move] for move in generator.moves
    )
    return out


# --------------------------------------------------------------------------
# Half two: exact equivariance and the parity split
# --------------------------------------------------------------------------


def exact_rows(
    generator: Generator, rates: Mapping[Tuple[str, int], Fraction]
) -> List[Dict[int, Fraction]]:
    """Row-oriented operator in exact rational arithmetic."""

    out: List[Dict[int, Fraction]] = []
    for source in range(generator.size):
        entries: Dict[int, Fraction] = {}
        diagonal = Fraction(0)
        for move, rate in rates.items():
            image = generator.target[move][source]
            if image is None or rate == 0:
                continue
            entries[image] = entries.get(image, Fraction(0)) + rate
            diagonal -= rate
        if diagonal != 0:
            entries[source] = entries.get(source, Fraction(0)) + diagonal
        out.append({key: value for key, value in entries.items() if value != 0})
    return out


def conjugate(rows: Sequence[Mapping[int, Fraction]], pi: Sequence[int]) -> List[Dict[int, Fraction]]:
    """``R K R`` for a permutation ``R``: entry ``(i,j)`` becomes ``(pi[i], pi[j])``."""

    out: List[Dict[int, Fraction]] = [dict() for _ in rows]
    for source, row in enumerate(rows):
        target = out[pi[source]]
        for destination, value in row.items():
            target[pi[destination]] = value
    return out


def rows_equal(
    left: Sequence[Mapping[int, Fraction]], right: Sequence[Mapping[int, Fraction]]
) -> bool:
    return all(dict(a) == dict(b) for a, b in zip(left, right))


def combine_rows(
    left: Sequence[Mapping[int, Fraction]],
    right: Sequence[Mapping[int, Fraction]],
    sign: int,
) -> List[Dict[int, Fraction]]:
    out = []
    for a, b in zip(left, right):
        merged = dict(a)
        for key, value in b.items():
            merged[key] = merged.get(key, Fraction(0)) + sign * value
        out.append({key: value / 2 for key, value in merged.items() if value != 0})
    return out


def frobenius_rows(rows: Sequence[Mapping[int, Fraction]]) -> float:
    return math.sqrt(float(sum(value * value for row in rows for value in row.values())))


def move_indicator(generator: Generator, operation: str, point: int) -> Dict[Tuple[str, int], Fraction]:
    return {
        move: (Fraction(1) if move == (operation, point) else Fraction(0))
        for move in generator.moves
    }


def equivariance(generator: Generator, k: int) -> Dict[str, Any]:
    """Exact ``R K R = K`` for the pencil, and the move-level reason.

    The operator identity is the thing the theorem needs, but the *reason* is
    worth recording separately: ``R`` maps the join at point ``p`` to the join at
    ``(k-1) - p`` and the detach at ``p`` to the detach at ``k - p``.  Uniform
    sums over ``p`` are therefore invariant, and a single-point tilt is not --
    which is the whole asymmetry between the declared pencil and ``H_single``.
    """

    width = generator.width
    pi = state_permutation(generator, reflection(width, k))
    joins = {move: (Fraction(1) if move[0] == "join" else Fraction(0)) for move in generator.moves}
    detaches = {move: (Fraction(1) if move[0] == "detach" else Fraction(0)) for move in generator.moves}
    baseline = {move: Fraction(1) for move in generator.moves}

    results = {}
    for name, rates in (("J", joins), ("D", detaches), ("G0", baseline)):
        rows = exact_rows(generator, rates)
        results[f"R_{name}_R_equals_{name}"] = rows_equal(conjugate(rows, pi), rows)

    # Move-level witness, exact and independent of the operator identity above.
    move_map = []
    for point in range(width):
        for operation, expected in (
            ("join", (k - 1 - point) % width),
            ("detach", (k - point) % width),
        ):
            rows = exact_rows(generator, move_indicator(generator, operation, point))
            image = exact_rows(generator, move_indicator(generator, operation, expected))
            move_map.append({
                "move": f"{operation}@{point}",
                "predicted_image": f"{operation}@{expected}",
                "conjugation_matches": rows_equal(conjugate(rows, pi), image),
            })
    results["move_conjugation"] = move_map
    results["all_moves_map_as_predicted"] = all(row["conjugation_matches"] for row in move_map)
    results["reflection_is_state_involution"] = is_involution(pi)
    return results


def parity_split(generator: Generator, k: int) -> Dict[str, Any]:
    """Split the single-point tilt into ``R``-even and ``R``-odd parts, exactly."""

    width = generator.width
    pi = state_permutation(generator, reflection(width, k))
    single = exact_rows(generator, move_indicator(generator, "join", 0))
    mirrored = conjugate(single, pi)
    even = combine_rows(single, mirrored, +1)
    odd = combine_rows(single, mirrored, -1)

    # The mirrored tilt should be the join at (k-1) - 0, checked independently.
    partner_point = (k - 1) % width
    partner = exact_rows(generator, move_indicator(generator, "join", partner_point))

    sum_back = [
        {key: value for key, value in
         {**{d: even[i].get(d, Fraction(0)) + odd[i].get(d, Fraction(0))
             for d in set(even[i]) | set(odd[i])}}.items() if value != 0}
        for i in range(generator.size)
    ]
    return {
        "mirror_partner_point": partner_point,
        "mirrored_single_is_the_partner_join": rows_equal(mirrored, partner),
        "R_Heven_R_equals_plus_Heven": rows_equal(conjugate(even, pi), even),
        "R_Hodd_R_equals_minus_Hodd": rows_equal(
            conjugate(odd, pi), [{d: -v for d, v in row.items()} for row in odd]
        ),
        "even_plus_odd_is_H_single": rows_equal(sum_back, single),
        "norm_H_single": frobenius_rows(single),
        "norm_H_even": frobenius_rows(even),
        "norm_H_odd": frobenius_rows(odd),
        "odd_share_of_norm": (
            frobenius_rows(odd) / frobenius_rows(single) if frobenius_rows(single) > 0 else 0.0
        ),
        "_even": even,
        "_odd": odd,
    }


# --------------------------------------------------------------------------
# The selection rule, checked pointwise in the time integrand
# --------------------------------------------------------------------------


def rows_to_float(rows: Sequence[Mapping[int, Fraction]]) -> List[List[Tuple[int, float]]]:
    return [sorted((key, float(value)) for key, value in row.items()) for row in rows]


def transpose_rows(
    rows: Sequence[Sequence[Tuple[int, float]]], size: int
) -> List[List[Tuple[int, float]]]:
    gathered: List[Dict[int, float]] = [dict() for _ in range(size)]
    for source, row in enumerate(rows):
        for destination, value in row:
            gathered[destination][source] = gathered[destination].get(source, 0.0) + value
    return [sorted(entry.items()) for entry in gathered]


class Propagator:
    """``exp(t A) v`` by uniformization, with the ``P^k v`` sequence cached.

    The cache is the reason the whole (s, t) grid is affordable at width 8: the
    Krylov-like sequence depends only on the vector, so every time on the grid is
    a reweighting of one sequence rather than a fresh matrix-exponential.
    """

    def __init__(self, rows: Sequence[Sequence[Tuple[int, float]]], size: int) -> None:
        # Uniformization rate: the largest exit rate, i.e. the most negative
        # diagonal entry.  Taking a larger rate is always safe (it only adds
        # Poisson terms); taking a smaller one would make ``I + A/rate`` have
        # negative entries and the series would stop being a probabilistic
        # average, which is what keeps it numerically stable.
        rate = 0.0
        for source, row in enumerate(rows):
            for column, value in row:
                if column == source:
                    rate = max(rate, -value)
        self.rate = rate if rate > 0 else 1.0
        self.size = size
        self.rows = rows
        self._cache: Dict[int, List[List[float]]] = {}

    def _sequence(self, key: int, vector: Sequence[float], terms: int) -> List[List[float]]:
        cached = self._cache.get(key)
        if cached is not None and len(cached) >= terms:
            return cached
        sequence = [list(vector)]
        current = list(vector)
        for _ in range(terms - 1):
            stepped = matvec(self.rows, current)
            current = [
                current[i] + stepped[i] / self.rate for i in range(self.size)
            ]
            sequence.append(current)
        self._cache[key] = sequence
        return sequence

    def terms_for(self, time: float) -> int:
        mean = self.rate * time
        terms, mass, weight = 1, math.exp(-mean), math.exp(-mean)
        while mass < 1.0 - POISSON_TAIL and terms < MAX_POISSON:
            weight *= mean / terms
            mass += weight
            terms += 1
        return terms + 1

    def apply(self, key: int, vector: Sequence[float], time: float) -> List[float]:
        if time == 0.0:
            return list(vector)
        terms = self.terms_for(time)
        sequence = self._sequence(key, vector, terms)
        mean = self.rate * time
        out = [0.0] * self.size
        weight = math.exp(-mean)
        for k in range(min(terms, len(sequence))):
            if weight > 0.0:
                row = sequence[k]
                for i in range(self.size):
                    out[i] += weight * row[i]
            weight *= mean / (k + 1)
        return out


def _relative(defect: Sequence[float], reference: Sequence[float]) -> float:
    scale = math.sqrt(sum(value * value for value in reference))
    if scale == 0.0:
        return 0.0
    return math.sqrt(sum(value * value for value in defect)) / scale


def parity_defect(vector: Sequence[float], pi: Sequence[int], sign: int) -> float:
    """How far ``vector`` is from the ``sign`` eigenspace of ``R``, relatively."""

    defect = [vector[i] - sign * vector[pi[i]] for i in range(len(vector))]
    return _relative(defect, vector) / 2


def selection_rule(
    generator: Generator, k: int, odd_rows: Sequence[Mapping[int, Fraction]]
) -> Dict[str, Any]:
    """The pointwise integrand ``mu^T e^{(t-s)G} H_odd e^{sG} f`` over the grid.

    Checked pointwise rather than after integration on purpose: the theorem says
    every integrand vanishes, so a quadrature that happened to cancel would be a
    weaker and more accident-prone confirmation.  Each pair also reports the two
    sector facts the vanishing rests on, so a failure says *which* link broke.
    """

    pi = state_permutation(generator, reflection(generator.width, k))
    baseline = generator.rows({move: 1.0 for move in generator.moves})
    forward = Propagator(baseline, generator.size)
    backward = Propagator(transpose_rows(baseline, generator.size), generator.size)
    odd = rows_to_float(odd_rows)

    readouts = [
        (name, [function(state) for state in generator.states])
        for name, function in READOUTS
    ]
    sources = source_distributions(generator)

    readout_parity = {
        name: parity_defect(values, pi, +1) for name, values in readouts
    }
    source_parity = {
        name: parity_defect(vector, pi, +1) for name, vector in sources
    }

    rows = []
    for t in LAGS:
        for fraction in SPLIT_FRACTIONS:
            s = t * fraction
            evolved = {
                name: forward.apply(index, values, s)
                for index, (name, values) in enumerate(readouts)
            }
            tilted = {name: matvec(odd, vector) for name, vector in evolved.items()}
            measures = {
                name: backward.apply(1000 + index, vector, t - s)
                for index, (name, vector) in enumerate(sources)
            }
            for source_name, measure in measures.items():
                for readout_name, image in tilted.items():
                    value = sum(measure[i] * image[i] for i in range(generator.size))
                    scale = (
                        math.sqrt(sum(v * v for v in measure))
                        * math.sqrt(sum(v * v for v in image))
                    )
                    rows.append({
                        "t": t,
                        "s": s,
                        "source": source_name,
                        "readout": readout_name,
                        "integrand": value,
                        "relative_integrand": (value / scale) if scale > 0 else 0.0,
                        "evolved_readout_even_defect": parity_defect(
                            evolved[readout_name], pi, +1
                        ),
                        "tilted_odd_defect": parity_defect(image, pi, -1),
                        "evolved_source_even_defect": parity_defect(measure, pi, +1),
                    })

    even_readouts = {name for name, defect in readout_parity.items() if defect < SECTOR_TOLERANCE}
    even_sources = {name for name, defect in source_parity.items() if defect < SECTOR_TOLERANCE}
    protected = [
        row for row in rows
        if row["source"] in even_sources and row["readout"] in even_readouts
    ]
    exposed = [
        row for row in rows
        if row["source"] in even_sources and row["readout"] not in even_readouts
    ]
    return {
        "readout_even_defect": readout_parity,
        "source_even_defect": source_parity,
        "even_readouts": sorted(even_readouts),
        "odd_containing_readouts": sorted(set(readout_parity) - even_readouts),
        "even_sources": sorted(even_sources),
        "protected_pairs": len(protected),
        "worst_protected_relative_integrand": max(
            (abs(row["relative_integrand"]) for row in protected), default=0.0
        ),
        "protected_all_vanish": all(
            abs(row["relative_integrand"]) < SECTOR_TOLERANCE for row in protected
        ),
        "exposed_pairs": len(exposed),
        "largest_exposed_relative_integrand": max(
            (abs(row["relative_integrand"]) for row in exposed), default=0.0
        ),
        "exposed_channel_is_visible": any(
            abs(row["relative_integrand"]) > 1e-6 for row in exposed
        ),
        "worst_sector_defect": max(
            (max(row["evolved_readout_even_defect"], row["tilted_odd_defect"],
                 row["evolved_source_even_defect"])
             for row in rows if row["readout"] in even_readouts),
            default=0.0,
        ),
    }


# --------------------------------------------------------------------------
# Phase B: the consequence -- the breaking direction enters at second order
# --------------------------------------------------------------------------


def tilted_rates(
    generator: Generator, k: int, kind: str, epsilon: float
) -> Dict[Tuple[str, int], float]:
    """Baseline rates with the named part of the single-point tilt applied.

    ``H_single`` raises the join at point 0.  Its mirror under ``R`` is the join
    at ``(k-1) mod w``, so the even part raises both by half and the odd part
    raises one while lowering the other.  Writing the three as rate vectors keeps
    every tilted operator an exact generator, which uniformization needs.
    """

    partner = (k - 1) % generator.width
    rates = {move: 1.0 for move in generator.moves}
    if kind == "none":
        return rates
    if kind == "single":
        rates[("join", 0)] += epsilon
    elif kind == "even":
        rates[("join", 0)] += epsilon / 2
        rates[("join", partner)] += epsilon / 2
    elif kind == "odd":
        rates[("join", 0)] += epsilon / 2
        rates[("join", partner)] -= epsilon / 2
    else:  # pragma: no cover - guarded by the caller
        raise ValueError(f"unknown tilt {kind!r}")
    _require(all(rate >= 0.0 for rate in rates.values()), "tilt left the generator cone")
    return rates


def responses(
    generator: Generator, rates: Mapping[Tuple[str, int], float],
    readouts: Sequence[Tuple[str, Sequence[float]]],
    sources: Sequence[Tuple[str, Sequence[float]]],
) -> Dict[Tuple[str, str, float], float]:
    propagator = Propagator(generator.rows(rates), generator.size)
    out: Dict[Tuple[str, str, float], float] = {}
    for index, (readout_name, values) in enumerate(readouts):
        for t in LAGS:
            evolved = propagator.apply(index, values, t)
            for source_name, measure in sources:
                out[(source_name, readout_name, t)] = sum(
                    measure[i] * evolved[i] for i in range(generator.size)
                )
    return out


def second_order(generator: Generator, k: int, even_readouts: Sequence[str]) -> Dict[str, Any]:
    """Fit the order in ``eps`` at which the odd direction reaches an even task.

    Two differences are measured, and they say different things.  ``odd_vs_none``
    is the theorem itself: turning on the pure breaking direction must not move
    an invariant task at first order.  ``single_vs_even`` is the practical
    consequence for #580 -- the part of the observed intervention that destroyed
    the exact quotient is the part the task barely feels.
    """

    readouts = [
        (name, [function(state) for state in generator.states])
        for name, function in READOUTS if name in set(even_readouts)
    ]
    sources = source_distributions(generator)
    base = responses(generator, tilted_rates(generator, k, "none", 0.0), readouts, sources)

    series: Dict[str, List[Tuple[float, float]]] = {"odd_vs_none": [], "single_vs_even": []}
    for epsilon in EPSILONS:
        odd = responses(generator, tilted_rates(generator, k, "odd", epsilon), readouts, sources)
        even = responses(generator, tilted_rates(generator, k, "even", epsilon), readouts, sources)
        single = responses(generator, tilted_rates(generator, k, "single", epsilon), readouts, sources)
        scale = math.sqrt(sum(value * value for value in base.values()))
        series["odd_vs_none"].append((
            epsilon,
            math.sqrt(sum((odd[key] - base[key]) ** 2 for key in base)) / scale,
        ))
        series["single_vs_even"].append((
            epsilon,
            math.sqrt(sum((single[key] - even[key]) ** 2 for key in base)) / scale,
        ))

    out: Dict[str, Any] = {"readouts_scored": [name for name, _ in readouts]}
    for label, points in series.items():
        usable = [(e, d) for e, d in points if d > 0]
        if len(usable) >= 2:
            (e0, d0), (e1, d1) = usable[0], usable[-1]
            slope = math.log(d1 / d0) / math.log(e1 / e0)
        else:
            slope = float("nan")
        out[label] = {
            "points": [{"epsilon": e, "relative_difference": d} for e, d in points],
            "log_log_slope": slope,
            "consistent_with_second_order": bool(abs(slope - 2.0) < 0.15),
        }
    # A first-order control: the even part is *not* invisible, so its own slope
    # must be 1.  Without this the second-order fits could be measuring a bug
    # that makes every difference small.
    first_order = []
    for epsilon in EPSILONS:
        even = responses(generator, tilted_rates(generator, k, "even", epsilon), readouts, sources)
        scale = math.sqrt(sum(value * value for value in base.values()))
        first_order.append((
            epsilon,
            math.sqrt(sum((even[key] - base[key]) ** 2 for key in base)) / scale,
        ))
    (e0, d0), (e1, d1) = first_order[0], first_order[-1]
    out["even_vs_none"] = {
        "points": [{"epsilon": e, "relative_difference": d} for e, d in first_order],
        "log_log_slope": math.log(d1 / d0) / math.log(e1 / e0) if d0 > 0 and d1 > 0 else float("nan"),
        "consistent_with_first_order": bool(
            d0 > 0 and d1 > 0 and abs(math.log(d1 / d0) / math.log(e1 / e0) - 1.0) < 0.15
        ),
    }
    return out


# --------------------------------------------------------------------------
# Assembly
# --------------------------------------------------------------------------


def width_report(width: int) -> Dict[str, Any]:
    generator = Generator(width)
    survey = reflection_survey(generator)
    k = survey["task_compatible_k"]
    _require(k is not None, f"width {width}: the declared dictionary does not name one reflection")
    split = parity_split(generator, k)
    rule = selection_rule(generator, k, split["_odd"])
    report = {
        "width": width,
        "states": generator.size,
        "task_compatible_reflection": f"i -> {k} - i",
        "reflection_survey": {
            key: value for key, value in survey.items() if key != "by_reflection"
        },
        "per_reflection_fixed_states": {
            row["k"]: row["fixed_states"] for row in survey["by_reflection"]
        },
        "orbit_count": burnside_check(generator, k),
        "lumping": lumping_comparison(generator, k),
        "equivariance": {
            key: value for key, value in equivariance(generator, k).items()
            if key != "move_conjugation"
        },
        "parity_split": {key: value for key, value in split.items() if not key.startswith("_")},
        "selection_rule": rule,
        "second_order": second_order(generator, k, rule["even_readouts"]),
    }
    return report


def decide(reports: Sequence[Mapping[str, Any]]) -> Dict[str, Any]:
    orbit_ok = all(r["orbit_count"]["matches_reported_r_positive"] for r in reports)
    partition_ok = all(r["lumping"]["D0"]["coarsest_equals_orbit_partition"] for r in reports)
    equivariant = all(
        r["equivariance"]["R_G0_R_equals_G0"] and r["equivariance"]["all_moves_map_as_predicted"]
        for r in reports
    )
    split_ok = all(
        r["parity_split"]["R_Hodd_R_equals_minus_Hodd"]
        and r["parity_split"]["R_Heven_R_equals_plus_Heven"]
        and r["parity_split"]["even_plus_odd_is_H_single"]
        for r in reports
    )
    protected = all(r["selection_rule"]["protected_all_vanish"] for r in reports)
    # The test has to be able to fail somewhere, or its passing means nothing.
    exposed_seen = any(r["selection_rule"]["exposed_channel_is_visible"] for r in reports)
    second = all(r["second_order"]["odd_vs_none"]["consistent_with_second_order"] for r in reports)
    first = all(r["second_order"]["even_vs_none"]["consistent_with_first_order"] for r in reports)

    if not (equivariant and split_ok):
        verdict = "SETUP_FAILED__BASELINE_IS_NOT_EQUIVARIANT_OR_THE_SPLIT_IS_WRONG"
    elif not exposed_seen:
        verdict = "TEST_IS_VACUOUS__NO_ODD_CHANNEL_PRESENT_TO_FALSIFY_THE_RULE"
    elif not protected:
        verdict = "SELECTION_RULE_FAILS__AN_INVARIANT_TASK_RESPONDS_AT_FIRST_ORDER"
    elif not (second and first):
        verdict = "SELECTION_RULE_HOLDS_BUT_THE_ORDER_LADDER_DISAGREES"
    elif orbit_ok and partition_ok:
        verdict = "SYMMETRY_QUOTIENT_PLUS_PARITY_SELECTION_RULE__GATE1_BRANCH_A"
    elif orbit_ok:
        verdict = "ORBIT_COUNT_MATCHES_BUT_THE_PARTITION_DIFFERS__GATE1_BRANCH_B"
    else:
        verdict = "ORBIT_ACCOUNT_REJECTED__REPAIR_THE_STATE_SEMANTICS_FIRST"

    return {
        "orbit_count_matches_reported_r_positive": orbit_ok,
        "coarsest_lumping_is_the_orbit_partition": partition_ok,
        "baseline_is_R_equivariant": equivariant,
        "parity_split_is_exact": split_ok,
        "invariant_tasks_have_zero_first_order_response": protected,
        "an_odd_channel_exists_so_the_test_can_fail": exposed_seen,
        "odd_direction_enters_at_second_order": second,
        "even_direction_enters_at_first_order": first,
        "verdict": verdict,
        "predicted_r_positive": {
            width: (catalan(width) + math.comb(width, width // 2)) // 2
            for width in (9, 10)
        },
        "claim_boundary": (
            "This is an exact finite symmetry statement about P398, not a "
            "percolation-threshold result.  The reflection is not a continuum "
            "spin label, and the small balanced order remains task-relative.  "
            "The orbit-count identity alone identifies nothing -- every "
            "reflection gives the same count -- so the load is carried by the "
            "partition equality and the selection rule, not by the formula."
        ),
    }


def assemble(widths: Sequence[int]) -> Dict[str, Any]:
    reports = [width_report(width) for width in widths]
    return {
        "schema": SCHEMA,
        "issue": ISSUE,
        "status": "exact symmetry/parity computation; no sampling, no new width, no fit",
        "widths": list(widths),
        "declared": {
            "dictionary_D0": list(D0_NAMES),
            "held_out_readouts": [name for name, _ in HELD_OUT_READOUTS],
            "lags": list(LAGS),
            "split_fractions": list(SPLIT_FRACTIONS),
            "epsilons": list(EPSILONS),
            "sector_tolerance": SECTOR_TOLERANCE,
        },
        "by_width": reports,
        "decision": decide(reports),
    }


def render(payload: Mapping[str, Any]) -> str:
    lines = [f"#{ISSUE} P398 reflection parity: is the breaking direction first-order invisible?", ""]
    lines.append(
        f"  {'w':>2} {'states':>7} {'R':>12} {'orbits':>7} {'r_pos':>6} {'P=orbit':>8}"
        f" {'|Hodd|/|H|':>11} {'prot.':>6} {'worst':>10} {'exposed':>9}"
    )
    for report in payload["by_width"]:
        rule = report["selection_rule"]
        lines.append(
            f"  {report['width']:>2} {report['states']:>7}"
            f" {report['task_compatible_reflection']:>12}"
            f" {report['orbit_count']['orbits_counted']:>7}"
            f" {str(report['orbit_count']['reported_r_positive']):>6}"
            f" {str(report['lumping']['D0']['coarsest_equals_orbit_partition']):>8}"
            f" {report['parity_split']['odd_share_of_norm']:>11.4f}"
            f" {rule['protected_pairs']:>6}"
            f" {rule['worst_protected_relative_integrand']:>10.2e}"
            f" {rule['largest_exposed_relative_integrand']:>9.3f}"
        )
    lines += ["", "  order ladder on invariant tasks (log-log slope over the declared epsilon grid)", ""]
    lines.append(f"  {'w':>2} {'odd vs none':>12} {'single vs even':>15} {'even vs none':>13}")
    for report in payload["by_width"]:
        second = report["second_order"]
        lines.append(
            f"  {report['width']:>2} {second['odd_vs_none']['log_log_slope']:>12.4f}"
            f" {second['single_vs_even']['log_log_slope']:>15.4f}"
            f" {second['even_vs_none']['log_log_slope']:>13.4f}"
        )
    for report in payload["by_width"]:
        odd_names = report["selection_rule"]["odd_containing_readouts"]
        if odd_names:
            lines.append(
                f"  w={report['width']}: odd-containing readout(s) {odd_names} -- "
                f"first-order response required and observed at "
                f"{report['selection_rule']['largest_exposed_relative_integrand']:.3f}"
            )
    decision = payload["decision"]
    lines += [
        "",
        f"predicted r_positive at widths 9, 10: {decision['predicted_r_positive']}",
        f"VERDICT: {decision['verdict']}",
    ]
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--widths", type=int, nargs="+", default=list(DEFAULT_WIDTHS))
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    payload = assemble(tuple(args.widths))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, default=float) + "\n", encoding="utf-8")
    print(render(payload))
    print()
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
