#!/usr/bin/env python3
"""Generate Pell-matched axis/diamond torus sizes.

Solutions of

    a^2 - 2 d^2 = +/- 1

pair an axis square torus (N=a^2, physical side a) with a pi/4 diamond
torus (N=2 d^2, physical side sqrt(2)d).  Their site counts differ by
exactly one while their physical side lengths converge rapidly.

The positive solutions are generated by repeated multiplication by 1+sqrt(2):

    (a', d') = (a + 2d, a + d).

Example:
    python scripts/pell_orientation_pairs.py --count 8
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def generate(count: int, skip_trivial: bool) -> list[dict[str, int | float]]:
    a, d = 1, 1
    rows: list[dict[str, int | float]] = []
    while len(rows) < count:
        pell = a * a - 2 * d * d
        if not skip_trivial or a >= 3:
            l_axis = float(a)
            l_diamond = math.sqrt(2.0) * d
            rows.append(
                {
                    "axis_a": a,
                    "diamond_d": d,
                    "pell": pell,
                    "axis_sites": a * a,
                    "diamond_sites": 2 * d * d,
                    "site_difference": a * a - 2 * d * d,
                    "axis_length": l_axis,
                    "diamond_length": l_diamond,
                    "relative_length_mismatch": (l_axis - l_diamond)
                    / ((l_axis + l_diamond) / 2.0),
                }
            )
        a, d = a + 2 * d, a + d
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=8)
    parser.add_argument(
        "--include-trivial",
        action="store_true",
        help="include the first (1,1) solution",
    )
    parser.add_argument("--json", type=Path, default=None)
    args = parser.parse_args()

    if args.count <= 0:
        raise SystemExit("--count must be positive")

    rows = generate(args.count, skip_trivial=not args.include_trivial)
    print(
        " axis  diamond   pell      N_axis   N_diamond   rel_length_mismatch"
    )
    for row in rows:
        print(
            f"{row['axis_a']:5d} {row['diamond_d']:8d} "
            f"{row['pell']:6d} {row['axis_sites']:12d} "
            f"{row['diamond_sites']:11d} "
            f"{row['relative_length_mismatch']:+.6e}"
        )

    if args.json is not None:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(json.dumps(rows, indent=2), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
